version: '3.8'

services:
  db:
    image: mariadb:10.6.2
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - './docker_data/mysql:/var/lib/mysql'

  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin'
    environment:
      PMA_HOST: db
    depends_on:
      - db
    ports:
      - '8080:80'