name: PaperChaseMC
version: 1.0
author: Kappa

api-version: 1.17

main: de.kappa.paperchase.Main

commands:
  pcspawn:
    description: Spawns a paperchase item
    usage: /pcspawn
  pcremove:
    description: Removes a paperchase item
    usage: /pcremove <optional mode>